
project_id = "rhjgagzstjzynvrakdyj"

[functions.whatsapp_instance_delete]
verify_jwt = false

[functions.webhook_qr_receiver]
verify_jwt = false

[functions.webhook_whatsapp_web]
verify_jwt = false

[functions.whatsapp_messaging_service]
verify_jwt = false

[functions.webhook_evolution]
verify_jwt = false

[functions.secure_whatsapp_service]
verify_jwt = true

[functions.ai_messaging_service]
verify_jwt = false

[functions.broadcast_campaign_manager]
verify_jwt = true

[functions.broadcast_scheduler]
verify_jwt = false

[functions.broadcast_sender]
verify_jwt = false

[functions.ai_message_consult]
verify_jwt = false

[functions.ai-message-consult]
verify_jwt = false

[functions.send_resend_invite]
verify_jwt = false

[functions.accept_invite]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
