#!/bin/bash
echo "🔧 CORREÇÃO DE TIMING DO WEBHOOK - USANDO NANO"
echo "============================================="
echo ""
echo "📋 INSTRUÇÕES PARA EDITAR O ARQUIVO server.js NA VPS:"
echo ""
echo "1️⃣ Conecte na VPS:"
echo "   ssh root@31.97.163.57"
echo ""
echo "2️⃣ Navegue para o diretório:"
echo "   cd /opt/whatsapp-puppeteer"
echo ""
echo "3️⃣ Faça backup do arquivo atual:"
echo "   cp server.js server.js.backup-$(date +%Y%m%d-%H%M%S)"
echo ""
echo "4️⃣ Edite o arquivo:"
echo "   nano server.js"
echo ""
echo "🎯 ENCONTRE A SEÇÃO (aproximadamente linha 160-180):"
echo "══════════════════════════════════════════════════════"
echo ""
echo "PROCURE POR esta linha:"
echo "   // Capturar QR Code e converter para Base64"
echo ""
echo "VOCÊ VERÁ algo assim:"
echo "   const qrElement = await page.$('[data-ref] canvas');"
echo "   if (qrElement) {"
echo "     const qrCodeBuffer = await qrElement.screenshot();"
echo "     const qrCodeBase64 = qrCodeBuffer.toString('base64');"
echo "     "
echo "     // ❌ PROBLEMA: Estas linhas estão ERRADAS"
echo "     session.qrCodeBase64 = qrCodeBase64;"
echo "     session.status = 'waiting_qr';  // ← ERRADO!"
echo "     "
echo "     // Notificar webhook com QR Code"
echo "     await notifyWebhook(session, {"
echo "       qrCode: qrCodeBase64"
echo "     });"
echo "   }"
echo ""
echo "🔧 SUBSTITUA essas linhas por:"
echo "══════════════════════════════════"
echo ""
echo "   const qrElement = await page.$('[data-ref] canvas');"
echo "   if (qrElement) {"
echo "     const qrCodeBuffer = await qrElement.screenshot();"
echo "     const qrCodeBase64 = \`data:image/png;base64,\${qrCodeBuffer.toString('base64')}\`;"
echo "     "
echo "     // ✅ CORREÇÃO: Só atualiza status quando QR estiver REALMENTE pronto"
echo "     session.qrCodeBase64 = qrCodeBase64;"
echo "     session.status = 'qr_ready';  // ← CORRETO!"
echo "     session.message = 'QR Code gerado com sucesso!';"
echo "     session.progress = 25;"
echo "     "
echo "     console.log(\`✅ [\${session.sessionId}] QR Code convertido para Base64 (\${qrCodeBase64.length} chars)\`);"
echo "     "
echo "     // 🎯 WEBHOOK APENAS quando QR estiver 100% disponível"
echo "     console.log(\`🔔 [\${session.sessionId}] Enviando webhook com QR Code...\`);"
echo "     await notifyWebhook(session, {"
echo "       qrCode: qrCodeBase64,"
echo "       status: 'qr_ready'  // Status que indica QR pronto"
echo "     });"
echo "     "
echo "     console.log(\`✅ [\${session.sessionId}] Webhook enviado com sucesso!\`);"
echo "   }"
echo ""
echo "💡 DICAS PARA USAR O NANO:"
echo "═════════════════════════"
echo "   • Ctrl + W = Buscar texto"
echo "   • Ctrl + O = Salvar arquivo"
echo "   • Ctrl + X = Sair do nano"
echo "   • Page Up/Down = Navegar no arquivo"
echo ""
echo "🔍 BUSCAR TEXTO NO NANO:"
echo "   1. Pressione Ctrl + W"
echo "   2. Digite: qrCodeBase64 = qrCodeBuffer"
echo "   3. Pressione Enter"
echo "   4. Edite as linhas conforme mostrado acima"
echo ""
echo "5️⃣ Após editar, salve e saia:"
echo "   • Ctrl + O (salvar)"
echo "   • Enter (confirmar nome)"
echo "   • Ctrl + X (sair)"
echo ""
echo "6️⃣ Reinicie o serviço:"
echo "   sudo systemctl restart whatsapp-puppeteer"
echo ""
echo "7️⃣ Verifique se funcionou:"
echo "   sudo systemctl status whatsapp-puppeteer"
echo "   curl -s http://localhost:3001/health | jq '.webhook_timing_fix'"
echo ""
echo "🎯 RESULTADO ESPERADO:"
echo "   • webhook_timing_fix: true"
echo "   • QR Code não será mais NULL no banco"
echo "   • Status 'qr_ready' apenas quando QR estiver pronto"
echo ""
echo "📞 Se precisar de ajuda:"
echo "   • Verifique os logs: journalctl -f -u whatsapp-puppeteer"
echo "   • Teste saúde: curl http://localhost:3001/health" 