#!/bin/bash
echo "📄 COMANDO PARA MOSTRAR TODO O CONTEÚDO DO SERVER.JS DA VPS"
echo "=========================================================="
echo ""
echo "Execute este comando no seu terminal:"
echo ""
echo "ssh root@31.97.163.57 \"cd /opt/whatsapp-puppeteer && cat server.js\""
echo ""
echo "OU se preferir com numeração de linhas:"
echo ""
echo "ssh root@31.97.163.57 \"cd /opt/whatsapp-puppeteer && cat -n server.js\""
echo ""
echo "OU para salvar em arquivo local:"
echo ""
echo "ssh root@31.97.163.57 \"cd /opt/whatsapp-puppeteer && cat server.js\" > server-vps-atual.js"
echo ""
echo "Depois cole o resultado aqui para analisarmos os conflitos!" 