
#!/bin/bash

echo "🔍 VERIFICAÇÃO DE TOKEN VPS - WhatsApp Server"
echo "=============================================="

# Conectar via SSH e verificar token
echo "📡 Conectando na VPS 31.97.24.222..."
echo ""

# Comando para verificar o token atual do servidor WhatsApp
echo "🔑 COMANDO PARA VERIFICAR TOKEN NO VPS:"
echo "ssh root@31.97.24.222"
echo ""
echo "Depois execute estes comandos na VPS:"
echo ""
echo "# 1. Verificar se servidor WhatsApp está rodando"
echo "pm2 list"
echo ""
echo "# 2. Ver logs do servidor WhatsApp"
echo "pm2 logs whatsapp-server --lines 10"
echo ""
echo "# 3. Verificar variável de ambiente do token"
echo "echo \$VPS_API_TOKEN"
echo ""
echo "# 4. Verificar arquivo de configuração do servidor"
echo "cat /root/whatsapp-server/.env 2>/dev/null || echo 'Arquivo .env não encontrado'"
echo ""
echo "# 5. Verificar token hardcoded no código"
echo "grep -r 'wapp_' /root/whatsapp-server/ 2>/dev/null || echo 'Token wapp_ não encontrado'"
echo ""
echo "# 6. Verificar configuração PM2"
echo "cat /root/.pm2/dump.pm2 | grep -A5 -B5 token || echo 'Token não encontrado no PM2'"
echo ""
echo "# 7. Testar endpoint de status diretamente"
echo "curl -s http://localhost:3001/health | jq . 2>/dev/null || curl -s http://localhost:3001/health"
echo ""
echo "# 8. Ver todas as variáveis de ambiente relacionadas"
echo "env | grep -i token"
echo ""
echo "# 9. Verificar arquivo de configuração principal"
echo "find /root -name '*.js' -o -name '*.json' -o -name '.env*' | xargs grep -l 'wapp_\\|token\\|auth' 2>/dev/null"
echo ""
echo "⚠️  IMPORTANTE: Procure por tokens que começam com 'wapp_'"
echo "📋 ANOTE o token encontrado e atualize o secret VPS_API_TOKEN no Supabase"
echo ""
echo "🔗 Link para atualizar secret:"
echo "https://supabase.com/dashboard/project/kigyebrhfoljnydfipcr/settings/functions"
