
#!/bin/bash

# COMANDOS MANUAIS PARA EXECUTAR NA VPS
echo "📋 COMANDOS MANUAIS PARA EXECUTAR NA VPS"
echo "========================================"
echo "📅 Data: $(date)"
echo "🎯 Objetivo: Comandos para copiar e colar manualmente"
echo ""

echo "🔧 INSTRUÇÕES:"
echo "1. Conecte na VPS via SSH"
echo "2. Copie e cole os comandos abaixo UM POR VEZ"
echo "3. Aguarde cada comando terminar antes do próximo"
echo ""

echo "# ==========================================="
echo "# PASSO 1: CRIAR DIRETÓRIO E NAVEGAR"
echo "# ==========================================="
echo "mkdir -p /root/restore-scripts"
echo "cd /root/restore-scripts"
echo ""

echo "# ==========================================="
echo "# PASSO 2: CRIAR SCRIPT DE LIMPEZA TOTAL"
echo "# ==========================================="
echo "nano vps-total-cleanup.sh"
echo "# (Cole o conteúdo do arquivo src/utils/vps-total-cleanup.sh)"
echo "# (Salve com Ctrl+X, depois Y, depois Enter)"
echo ""

echo "# ==========================================="
echo "# PASSO 3: CRIAR SCRIPT DE INSTALAÇÃO LIMPA"
echo "# ==========================================="
echo "nano vps-clean-installation.sh"
echo "# (Cole o conteúdo do arquivo src/utils/vps-clean-installation.sh)"
echo "# (Salve com Ctrl+X, depois Y, depois Enter)"
echo ""

echo "# ==========================================="
echo "# PASSO 4: CRIAR SCRIPT DO SERVIDOR ORIGINAL"
echo "# ==========================================="
echo "nano vps-original-server.sh"
echo "# (Cole o conteúdo do arquivo src/utils/vps-original-server.sh)"
echo "# (Salve com Ctrl+X, depois Y, depois Enter)"
echo ""

echo "# ==========================================="
echo "# PASSO 5: CRIAR SCRIPT DE TESTE"
echo "# ==========================================="
echo "nano vps-original-test.sh"
echo "# (Cole o conteúdo do arquivo src/utils/vps-original-test.sh)"
echo "# (Salve com Ctrl+X, depois Y, depois Enter)"
echo ""

echo "# ==========================================="
echo "# PASSO 6: CRIAR SCRIPT DE RESTAURAÇÃO COMPLETA"
echo "# ==========================================="
echo "nano vps-complete-restore.sh"
echo "# (Cole o conteúdo do arquivo src/utils/vps-complete-restore.sh)"
echo "# (Salve com Ctrl+X, depois Y, depois Enter)"
echo ""

echo "# ==========================================="
echo "# PASSO 7: DAR PERMISSÕES DE EXECUÇÃO"
echo "# ==========================================="
echo "chmod +x vps-total-cleanup.sh"
echo "chmod +x vps-clean-installation.sh"
echo "chmod +x vps-original-server.sh"
echo "chmod +x vps-original-test.sh"
echo "chmod +x vps-complete-restore.sh"
echo ""

echo "# ==========================================="
echo "# PASSO 8: EXECUTAR RESTAURAÇÃO AUTOMÁTICA"
echo "# ==========================================="
echo "bash vps-complete-restore.sh"
echo "# (Este comando executará toda a sequência automaticamente)"
echo ""

echo "# ==========================================="
echo "# OU EXECUTAR MANUALMENTE PASSO A PASSO:"
echo "# ==========================================="
echo "# bash vps-total-cleanup.sh"
echo "# (Digite 'ZERAR TUDO' quando solicitado)"
echo "# bash vps-clean-installation.sh"
echo "# bash vps-original-server.sh"
echo "# bash vps-original-test.sh"
echo ""

echo "# ==========================================="
echo "# VERIFICAÇÕES FINAIS:"
echo "# ==========================================="
echo "curl http://localhost:3001/health"
echo "pm2 status"
echo "pm2 logs whatsapp-original-3001"
echo ""

echo "📋 RESUMO DOS ARQUIVOS A CRIAR:"
echo "   1. vps-total-cleanup.sh"
echo "   2. vps-clean-installation.sh" 
echo "   3. vps-original-server.sh"
echo "   4. vps-original-test.sh"
echo "   5. vps-complete-restore.sh"
echo ""

echo "⚠️ IMPORTANTE:"
echo "   - Execute os comandos UM POR VEZ"
echo "   - Aguarde cada comando terminar"
echo "   - O script de limpeza APAGA TUDO"
echo "   - Use Ctrl+C para interromper se necessário"
echo ""

echo "🚀 RESULTADO ESPERADO:"
echo "   Servidor WhatsApp original funcionando na porta 3001"
echo "   Acessível via: http://31.97.24.222:3001/health"
