
#!/bin/bash

# INSTALADOR MANUAL SIMPLIFICADO - COMANDOS PARA NANO
echo "📋 INSTALADOR MANUAL VPS - COMANDOS PARA NANO"
echo "============================================="

echo ""
echo "🔧 EXECUTE ESTES COMANDOS NA SUA VPS:"
echo "====================================="

echo ""
echo "# 1. Criar diretório e navegar"
echo "mkdir -p /root/forensic-scripts"
echo "cd /root/forensic-scripts"

echo ""
echo "# 2. Criar script de análise forense"
echo "nano vps-forensic-analysis.sh"
echo "# Cole o conteúdo do arquivo src/utils/vps-forensic-analysis.sh"
echo "# Salve com Ctrl+X, Y, Enter"

echo ""
echo "# 3. Criar script de limpeza radical"
echo "nano vps-radical-cleanup.sh"
echo "# Cole o conteúdo do arquivo src/utils/vps-radical-cleanup.sh"
echo "# Salve com Ctrl+X, Y, Enter"

echo ""
echo "# 4. Criar script de instalação controlada"
echo "nano vps-controlled-installation.sh"
echo "# Cole o conteúdo do arquivo src/utils/vps-controlled-installation.sh"
echo "# Salve com Ctrl+X, Y, Enter"

echo ""
echo "# 5. Criar script de servidor otimizado"
echo "nano vps-optimized-server.sh"
echo "# Cole o conteúdo do arquivo src/utils/vps-optimized-server.sh"
echo "# Salve com Ctrl+X, Y, Enter"

echo ""
echo "# 6. Criar script de teste abrangente"
echo "nano vps-comprehensive-test.sh"
echo "# Cole o conteúdo do arquivo src/utils/vps-comprehensive-test.sh"
echo "# Salve com Ctrl+X, Y, Enter"

echo ""
echo "# 7. Dar permissões de execução"
echo "chmod +x vps-forensic-analysis.sh"
echo "chmod +x vps-radical-cleanup.sh"
echo "chmod +x vps-controlled-installation.sh"
echo "chmod +x vps-optimized-server.sh"
echo "chmod +x vps-comprehensive-test.sh"

echo ""
echo "# 8. EXECUTAR A SEQUÊNCIA DE CORREÇÃO:"
echo "bash vps-forensic-analysis.sh"
echo "# (Revisar output antes de continuar)"
echo ""
echo "bash vps-radical-cleanup.sh"
echo "# (Digite 'CONFIRMAR' quando solicitado)"
echo ""
echo "bash vps-controlled-installation.sh"
echo ""
echo "bash vps-optimized-server.sh"
echo ""
echo "bash vps-comprehensive-test.sh"

echo ""
echo "🎯 ORDEM DE EXECUÇÃO RECOMENDADA:"
echo "1. Análise Forense (vps-forensic-analysis.sh)"
echo "2. Limpeza Radical (vps-radical-cleanup.sh) - IRREVERSÍVEL!"
echo "3. Instalação Controlada (vps-controlled-installation.sh)"
echo "4. Servidor Otimizado (vps-optimized-server.sh)"
echo "5. Teste Abrangente (vps-comprehensive-test.sh)"

echo ""
echo "⚠️ IMPORTANTE:"
echo "- Execute um script por vez"
echo "- Aguarde cada script finalizar antes do próximo"
echo "- Revise o output de cada fase"
echo "- O script de limpeza é IRREVERSÍVEL"
echo "- Use Ctrl+C para interromper se necessário"

echo ""
echo "📋 COMANDOS NANO ÚTEIS:"
echo "- Ctrl+X: Sair"
echo "- Y: Confirmar salvamento"
echo "- Enter: Confirmar nome do arquivo"
echo "- Ctrl+K: Deletar linha"
echo "- Ctrl+U: Colar linha"

echo ""
echo "🚀 PRONTOS PARA COMEÇAR!"
echo "Conecte na VPS e execute os comandos acima"
